# Generated by Django 6.0.6 on 2026-07-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='budget',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
