# Generated by Django 6.0.6 on 2026-07-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='service',
            field=models.CharField(choices=[('Website Development', 'Website Development'), ('Landing Page', 'Landing Page'), ('Logo Design', 'Logo Design'), ('Photo Editing', 'Photo Editing'), ('Video Editing', 'Video Editing')], max_length=50),
        ),
    ]
