# Generated by Django 6.0.6 on 2026-07-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='project_file',
            field=models.FileField(blank=True, null=True, upload_to='orders/'),
        ),
    ]
